export const FETCH_HOME_START = "FETCH_HOME_START"
export const FETCH_HOME_SUCCESS = "FETCH_HOME_SUCCESS"
export const FETCH_HOME_FAIL = "FETCH_HOME_FAIL"
export const FETCH_HOME_SHOW_MODAL = "FETCH_HOME_SHOW_MODAL"

export const FETCH_DETAIL_START = "FETCH_DETAIL_START"
export const FETCH_DETAIL_SUCCESS = "FETCH_DETAIL_SUCCESS"
export const FETCH_DETAIL_FAIL = "FETCH_DETAIL_FAIL"
